### ISSUE TITLE
Doc 17 and 18 missing

### ISSUE THREAD

**Issue by MoHu3** [bundesverfassung-oesterreich/bv-working-data#9]
Docs 17 and 18 are missing in Oxygen

**Comment by cfhaak** [comment]
@MoHu3 
They don't get exported, since they are missing metadata. There are no metadata for bv_doc_id__17 at all. Please add them accordingly, if this is a legit doc Maybe ask @RdLein  for help, if you don't find the right info.  bv_doc_id__18 is just missing the id of the matching transkribus entity. Just add the id and it will be exported.

**Comment by cfhaak** [comment]
(I'm talking about baserow.)

**Comment by cfhaak** [comment]
There are more then these two docs missing metadata. You can always see those with issues in the recent export Workflow run.
E.g.:
https://github.com/bundesverfassung-oesterreich/bv-transkribus-export/actions/runs/8681429217/job/23804016100#step:5:98
https://github.com/bundesverfassung-oesterreich/bv-transkribus-export/actions/runs/8681429217/job/23804016100#step:5:129
https://github.com/bundesverfassung-oesterreich/bv-transkribus-export/actions/runs/8681429217/job/23804016100#step:5:136
https://github.com/bundesverfassung-oesterreich/bv-transkribus-export/actions/runs/8681429217/job/23804016100#step:5:236
https://github.com/bundesverfassung-oesterreich/bv-transkribus-export/actions/runs/8681429217/job/23804016100#step:5:255

(Could be, that some are from Set B/C …)

**Comment by MoHu3** [comment]
we cant work with doc 18 since it is the handwritten one and we didnt have a recognized text for that
